### PR TITLE
SharePoint migration deep links

### PR DESCRIPTION
**Pull request by lhcole613**
FREELANCERS: Please do NOT merge.

@kaarins Please review 5 SharePoint PRs and return to me for changes or merge to the private repos if they're ready. Thank you!

### CODE REVIEW

**Comment by kaarins** [comment]
@lhcole613 for some reason "Migration Manager" got changed to "Migration center" in this update. Can you please change all instances to "Migration Manager"? Thanks!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by JohanFreelancer9** [comment]
Copy review - approved once @kaarins's request has been implemented.

**Pull request merged**
