### PR TITLE
Content fix on prepare-to-back-up-and-restore.md

### PR DESCRIPTION
**Pull request by esjimenezp**
A paragraph contains an incomprehensible context.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr can you confirm - can you use a backup created in one version to upgrade to a higher version?

**Comment by MikePlumleyMSFT** [comment]
@tseward do you happen to know the answer to this one?

**Comment by tseward** [comment]
@MikePlumleyMSFT in the context of using backup from Central Admin or `Backup-SPFarm`, that is correct, you cannot backup and restore to a new version of SharePoint, one needs to go through the [upgrade process](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/overview-of-the-upgrade-process-2019).

**Comment by MikePlumleyMSFT** [comment]
Thanks, @tseward.

**Pull request merged**
