### PR TITLE
Update Prepare-IE11.md

### PR DESCRIPTION
**Pull request by MattEEvans**
Added mention of View in File Explorer and updated the messaging about this and Open with Explorer

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by MattEEvans** [comment]
Hi Manuela,

Is there a way for me to pull this back or cancel the request? This process is taking too long. I'm a writer for Microsoft 365 at Microsoft, but new to authoring on docs.microsoft.com. I only made a few minor changes to this already published article, but I made the mistake of forgetting to add review to the docs article URL (https://review.docs.microsoft.com) before I edited.
I'd rather not take the time on a copy edit, if possible. The article had a 95 score from Acrolinx last time I checked.

Thanks,


***@***.***D76CFC.AB49AE10]
Matt Evans (Office Content)
Senior Technical Writer, E + D Marvel Team
Helping people win the moment
***@***.******@***.***> | 425-703-6942

**Review by JohanFreelancer9 — APPROVED** [review]
@MattEEvans - The copy looks good but if you want to cancel the pull request, you can simply close it. Hope it helps. Many thanks.

**Comment by MattEEvans** [comment]
Never mind. I'll do this over the right way.

**Pull request closed without merging**
