### PR TITLE
Remove double quotes

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3583

aligning to other articles -> https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/0e4a345e80d685f8e65e34e8197f5df0980945c6/SharePoint/SharePointOnline/exclude-or-uninstall-previous-sync-client.md

to avoid confusion if directly used in .reg files

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@get-itips this PR also removes the closing code formatting character ( ` ).

**Comment by get-itips** [comment]
> @get-itips this PR also removes the closing code formatting character ( ` ).

My mistake, I'll fix that, thanks!

**Comment by get-itips** [comment]
@MikePlumleyMSFT fixed, thanks

**Pull request merged**
