### PR TITLE
Update control-access-from-unmanaged-devices.md

### PR DESCRIPTION
**Pull request by tseward**
Remove wayward comma.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tseward

**Comment by scanum** [comment]
@kaarins Hi Kaarin, wondering if you could review @JohanFreelancer9 comment regarding the initial comma. Thanks!

**Comment by kaarins** [comment]
The comma is there by design as JohanFreelancer noted. Thanks!

**Pull request closed without merging**
