### PR TITLE
Update control-access-from-unmanaged-devices.md

### PR DESCRIPTION
**Pull request by they007**
Corrected example command. 
Incorrect command:
,(Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.**spgrid**.com/personal/") | Set-**SPOTenant** -ConditionalAccessPolicy AllowLimitedAccess

SPGrid.com is not a correct URL.
The 2nd command here should be Set-SPOSite and not SPOTenant as we are getting site objects and not tenant objects.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by kaarins** [comment]
I made a couple of the changes and am in discussion with the feature team about this command.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, thanks for letting us know. Please keep us updated. Appreciate all your help!

**Comment by scanum** [comment]
@kaarins any updates on this issue? Thanks!

**Comment by kaarins** [comment]
This issue has been fixed in a different pull request. Thanks!

**Pull request closed without merging**
