### PR TITLE
Adding link as suggested on #1321

### PR DESCRIPTION
**Pull request by j0rt3g4**
Added llink as important note #1321

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!

**Comment by MikePlumleyMSFT** [comment]
@j0rt3g4 this article has no relationship to issue #1321

**Comment by j0rt3g4** [comment]
Checking

**Comment by j0rt3g4** [comment]
Checking.

@MikePlumleyMSFT  What is the link that the user is requesting to add then?

**Pull request closed without merging**
