### PR TITLE
Fixed wrong cmdlet control-access-from-unmanaged-devices.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1866

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by dariomws** [comment]
> Copy review - copy is fine, but please confirm that Line 161 is still correct. The initial comma is now removed, but the line states "The initial comma and the parentheses are required..."

Added back the initial comma, thank you for noticing that.

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kaarins** [comment]
This cmdlet is passing the sites as an array to Set-SPOTenant (https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps). If you search, you can see that ConditionalAccessPolicy is also a parameter for Set-SPOTenant.

**Pull request closed without merging**
