### PR TITLE
Adding 2016 in the tune script heading

### PR DESCRIPTION
**Pull request by mikelee-msft**

### CODE REVIEW

**Comment by scanum** [comment]
@Techwriter40 Hi Kirk, could you please check and merge if correct? Thanks

**Comment by mikelee-msft** [comment]
> This article applies to all versions of SharePoint, so the requested change is not valid. It needs to be SharePoint Server, not accepting change at this time.

The section I edited only applies to 2016. There is a 2103 a section below and soon I will add a 2019 section.

**Comment by scanum** [comment]
@mikelee-msft Any updates on this?

**Comment by mikelee-msft** [comment]
> @mikelee-msft Any updates on this?

Did the changes go through ?

**Pull request merged**
