### PR TITLE
Transpose table

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3251

@JoanneHendrickson The table _migration offering_ looks better read if transposed, can you review please? Thank you

### CODE REVIEW

**Comment by scanum** [comment]
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@JoanneHendrickson can you please review?

**Comment by get-itips** [comment]
@JoanneHendrickson Can you please review and merge? Thank you

**Comment by get-itips** [comment]
@JoanneHendrickson

**Pull request merged**
