### PR TITLE
Update control-access-from-unmanaged-devices.md

### PR DESCRIPTION
**Pull request by nanddeepn**
In section "Block or limit access to a specific SharePoint site or OneDrive" step 9, "To update multiple sites at once, use the following command as an example:"
Updated the cmdlet (Get-SPOSite -IncludePersonalSite) with below changes:

1. Removed leading comma from the command.
2. Corrected filter condition by adding missing ' at the end.
3. Url format is made generic as '-my.sharepoint.com/personal/'

### CODE REVIEW

**Comment by nanddeepn** [comment]
Hi @kaarins,
Can you please help with the merge.

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kaarins** [comment]
I believe that the leading comma is necessary as noted in the article for running this cmdlet as a batch request. I'm confirming the changes with the feature lead.

**Comment by nanddeepn** [comment]
There are couple of observations.

1. Instead of Set-SPOTenant it should be to Set-SPOSite.


2. Leading Comma is unnecessary


I have raised new PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1312 to resolve this. Please review. Thanks!

**Pull request closed without merging**
