### PR TITLE
Remove extra backtick from code block

### PR DESCRIPTION
**Pull request by sassdawe**
Code block had two extra backtick characters

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@nimishasatapathy PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by nimishasatapathy — APPROVED** [review]
Yes the change looks good.

**Pull request merged**
