### PR TITLE
Improve wording

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3887

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@WayneEwington 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by WayneEwington** [comment]
Not quite sure why this was assigned to me, so have removed myself

**Comment by scanum** [comment]
@tiburd hope all is going well. Could you please help with this PR?

**Comment by tiburd** [comment]
@WayneEwington 
Hi Wayne,
The metadata shows you as the article reviewer. Can you please review the changes in the PR and then @ mention me to let us know whether the changes are accurate and approved?
Thank you!

**Comment by tiburd** [comment]
Reviewed and confirmed changes

**Pull request merged**
