### PR TITLE
Adjusting req permissions

### PR DESCRIPTION
**Pull request by get-itips**
instructions will fail if connecting only as a SharePoint administrator
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2804

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@scanum Can you ask to be merged? Thanks

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@kaarins Can you kindly review and merge, please? Thanks

**Comment by get-itips** [comment]
@kaarins Can this be merged? Thank you

**Pull request merged**
