### PR TITLE
Added link to sharepoint-migration-identity-mapping-tool-azure-active-direct…

### PR DESCRIPTION
**Pull request by dariomws**
…ory-identity-scan.md

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2202.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
@JoanneHendrickson could you please check and merge? Thanks!

**Comment by dariomws** [comment]
@JoanneHendrickson could you please check and merge? Thanks!

**Pull request merged**
