### PR TITLE
Update manage-the-distributed-cache-service.md

### PR DESCRIPTION
**Pull request by tseward**
Many formatting fixes and removal of non-working links. Fix for #510

### CODE REVIEW

**Comment by kenwith** [comment]
@MikePlumleyMSFT - I think @Techwriter40 (Kirk) had a project awhile back that went through and added the "PS C:>" to all of the examples.. :)    Maybe check with him so not going back and forth? On the Skype side we are avoiding the "PS C:>" too so that people can 'copy code' and paste it and run it.

**Comment by tseward** [comment]
@kenwith @MikePlumleyMSFT Yeah that would be great to know. I made the SP cmdlet documentation consistent by adding PS C:\\> to all of the examples... That would be an easy one-time fix if that is the chosen direction.

**Comment by Techwriter40** [comment]
I am ok with it as long as in the instructions we clearly state to run the cmdlet from a windows powershell command prompt.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @Techwriter40, in that case let's remove them. @kenwith, do you want to set up a project for handling examples beyond this PR?

**Pull request merged**
