### PR TITLE
adding MC270671 step

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2977

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by get-itips** [comment]
@SerdarSoysal can you please check and merge? Thanks

**Comment by MikePlumleyMSFT** [comment]
@cts-mbiswas can you review?

**Comment by get-itips** [comment]
@MikePlumleyMSFT @cts-mbiswas Can you review this? thanks

**Comment by get-itips** [comment]
@tiburd @SerdarSoysal can you help me get this merged? Thank you :)

**Review by cts-mbiswas — APPROVED** [review]

**Pull request merged**
