### PR TITLE
fix misspelling in ms.topic: conceptual

### PR DESCRIPTION
**Pull request by ReQ6W7rFnaBxyfb**
If this PR is accepted, please label it as "hacktoberfest-accepted" or classify the repository with the "hacktoberfest" topic. Thanks! 
https://hacktoberfest.digitalocean.com/hacktoberfest-update

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by ReQ6W7rFnaBxyfb** [comment]
@SerdarSoysal This is ready to merge, I think...

**Comment by ReQ6W7rFnaBxyfb** [comment]
@scanum This is ready to merge, I think...

**Comment by ReQ6W7rFnaBxyfb** [comment]
Closing this and deleting the branch.

**Pull request closed without merging**
