### PR TITLE
SEO edits for SharePoint Migration Tool

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited the metadata title tag. Old title was likely fine, but the new recommendation brings in the "download" keyword and highlights the additional resources.

Edited description to add keywords.

@DaniHalfin

### CODE REVIEW

**Comment by JoanneHendrickson** [comment]
@danihalfin  remove the reference to "other tools."  Having download in the title is fine, but this should be sharePoint Migration download and overview/introduction to the product.

**Comment by DaniHalfin** [comment]
@jdmartinez36 - can you follow up on the feedback above?

**Comment by jdmartinez36** [comment]
Hi @JoanneHendrickson 

I've edited the title and description (removed the "other tools") based on your feedback. Let me know if these changes are what you had in mind.

**Comment by jdmartinez36** [comment]
@DaniHalfin 

Made edits, asked Joanne to verify since the edits necessitated a change to the description wording.

**Comment by JoanneHendrickson** [comment]
@DaniHalfin  looks good.

**Comment by JoanneHendrickson** [comment]
@DaniHalfin  Looks fine.

**Pull request merged**
