### PR TITLE
Update mover-create-migration-csv.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2441
Fixed examples

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Hi @lindspea - If the examples changes, surely Lines 46, 47, and 50 need to change as well? Please have a look and change if necessary.

**Comment by lindspea** [comment]
> Hi @lindspea - If the examples changes, surely Lines 46, 47, and 50 need to change as well? Please have a look and change if necessary.

Thanks @JohanFreelancer9, not too sure about 46 and 47 as it's the source path, but I've changed line 50. Will see what the author says.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
