### PR TITLE
Issue #1548

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving issue #1548 changing SQLIO

Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!

### CODE REVIEW

**Comment by tseward** [comment]
It's not as simple as that. The article needs to be re-written with DiskSpd in mind. Just one example, the `-k` switch isn't valid... and the tests/results need to be re-written.

**Comment by pamgreen-msft** [comment]
Hi @tseward , @ABloesch and Yi Zhang (will be in GitHub soon) can assist with this issue. @ABloesch already confirmed the tool correction part is accurate.

**Comment by MSFT-yiz** [comment]
@tseward has a good point. Because of the tool change, we need to check the accuracy of content related to DiskSpd.

**Comment by MSFT-Tilia** [comment]
Hi @pamgreen-msft @MikePlumleyMSFT 
I'm looking at this PR's file changes. The command lines using DiskSpd proposed by the PR are incorrect. Maybe you can help assign this to me and I'll submit changes later.

**Comment by MSFT-Tilia** [comment]
created a new PR #1740 for this issue.

**Comment by MikePlumleyMSFT** [comment]
Closing in favor of the new PR.

**Pull request closed without merging**
