### PR TITLE
Fixing typo and other sentence

### PR DESCRIPTION
**Pull request by j0rt3g4**
Issue #1142 with fixes from @JohanFreelancer9

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by MikePlumleyMSFT** [comment]
I don't see any changes in this PR.

**Comment by j0rt3g4** [comment]
Hello @MikeBazMSFT  the changes can be seen here:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1144/files

**Comment by MikePlumleyMSFT** [comment]
[PR 1144](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1144/files) was previously merged. Closing this one since there are no changes to merge.

**Pull request closed without merging**
