### PR TITLE
Add OneDrive Timeline of OneDrive Deletion - conceptual art

### PR DESCRIPTION
**Pull request by jackwi-alt**

### CODE REVIEW

**Comment by kaarins** [comment]
Hi Jack, It looks like you added the image to the media folder but didn't add the link to the article. You probably want to put both changes in this pull request. Thanks!

**Comment by jackwi-alt** [comment]
Hi Kaarin:

I did add the link to the article but it looks like it may have appeared in a separate PR 2172 under my jackwi-alt-patch-1 branch. Let me re-work this.

-Jack

**Comment by kaarins** [comment]
Yes, I just saw it. One is a pull request to the public repo and one to the private, so this could cause problems. I would put both changes in the same pull request.

**Comment by jackwi-alt** [comment]
When I incorporated the png into the media folder, GitHub generated a new branch, jackwi-alt-patch-1-1. I’m not seeing that branch in my dropdown in the OfficeDocs-SharePoint-pr repo. Is there an easy way to incorporate the article upgrade into the same PR 1933? Would like to commit to the same branch, naturally, rather than create two PR in both the private and public repos as you’ve called out.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Pull request merged**
