### PR TITLE
Proposing adding expected time

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2975

based on own experience

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by MikePlumleyMSFT** [comment]
@get-itips this note is under "Limit access." Do you know if it applies to "Block access" as well? There's already a note under "Block access" about time for the policy to take effect when you turn it on. Wondering if we can combine notes, and if this needs to be called out in both sections.

**Comment by get-itips** [comment]
@MikePlumleyMSFT Thanks for your review.
Specifically tested under the _from_ Limit Access _to_ Full Access (aka turning the limits off), however this probably applies to both scenarios.
I can test with the block access to Full access as well to check if the waiting time is the same.

**Comment by get-itips** [comment]
@MikePlumleyMSFT Mike, I tested the _from_ Block _to_ Full access scenario and I only had to wait a couple of minutes for it to become effective. So it seems this only happens in the described scenario.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @get-itips.

**Pull request merged**
