### PR TITLE
Update to HKLM to match other paths

### PR DESCRIPTION
**Pull request by samtmagee**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@gacarini PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by gacarini — APPROVED** [review]
Looks good to me.

**Comment by scanum** [comment]
hi @gacarini Thanks! We will need your help with merging. Thanks!

**Review by gacarini — APPROVED** [review]

**Comment by gacarini** [comment]
> hi @gacarini Thanks! We will need your help with merging. Thanks!

@scanum I approved the PR but I'm not sure how to merge it. I've only merged my own changes.

**Pull request merged**
