### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2810

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@scanum Can you ask for merge? Thank you!

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@kaarins Can you kindly review and merge, please? Thanks

**Comment by get-itips** [comment]
@kaarins Can this be merged? thank you

**Comment by kaarins** [comment]
Already fixed!

**Pull request closed without merging**
