### PR TITLE
Changed instructions how to handle when Feature CustomTiles is not available

### PR DESCRIPTION
**Pull request by KoenZomers**
The instructions stated to add the Feature CustomTiles when it was not available. This is confusing as this feature comes with Feature Pack 1 and is not just available. So I changed the instructions to validate that the SharePoint farm is patched with at least Feature Pack 1 instead.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Good point @tseward, I'll update the text.

**Comment by KoenZomers** [comment]
@tseward, on second thought, it doesn't make sense to provide a download link to the first CU containing Feature Pack 1. We generally recommend to keep your farm patched with the latest CU and all CUs after the release of Feature Pack 1 contain Feature Pack 1. It's not feasible to keep updating this document every month to point to the latest CU. I did update the text to make mention of the CU month in which Feature Pack 1 was released, but did not add download links to that specific CU.

**Comment by tseward** [comment]
Correct, the recommendation is to stay up to date on a monthly basis. I might just mention the minimum requirements, e.g. KBnnnnnnn.

The problem with build numbers is they have no context unless you have a source for those numbers -- and those sources are maintained by the community rather than Microsoft. It might be worth just saying something along the lines of 'minimum of Feature Pack 1, first included in KBnnnnnnn' or similar.

**Comment by KoenZomers** [comment]
Agree. Did you check the update I've done to this PR based on your previous comments? I believe that is sufficient in this matter.

**Comment by tseward** [comment]
Yep, I think that looks good.

**Comment by kenwith** [comment]
@KoenZomers and @tseward thanks for collaboration and getting these fixed. Merged! Much appreciated!

**Pull request merged**
