### PR TITLE
Update hardware-and-software-requirements-2019.md

### PR DESCRIPTION
**Pull request by mikelee-msft**

### CODE REVIEW

**Comment by kenwith** [comment]
@mikelee-msft - I wonder if we want to link to the download page instead of the download directly? That way people can see the requirements for the download? What do you think?

**Comment by kenwith** [comment]
CC @Techwriter40

**Comment by mikelee-msft** [comment]
I agree with that. The link would be "https://www.microsoft.com/en-us/download/details.aspx?id=56041"  However, we should call out that the "\x64\sqlncli.msi" is required from within Feature Pack 4.

So may be the display name should be:

Microsoft SQL Server 2012 SP4 Feature Pack - Native Client (\x64\sqlncli.msi)
With link "https://www.microsoft.com/en-us/download/details.aspx?id=56041"

**Comment by kenwith** [comment]
Sounds good, I made some edits on your fork. Let me know what you think. You can click on the Files Changed at the top to see the changes. Should I go ahead and merge?

**Comment by kenwith** [comment]
Oh, made one more minor change.. I removed the   en-us   from URL.. so then it will use whatever language the persons browser is using instead of directly en-us.

**Comment by mikelee-msft** [comment]
yes! Good call!

**Pull request merged**
