### PR TITLE
Broken link manage-search-schema.md

### PR DESCRIPTION
**Pull request by esjimenezp**
The link on Introducing Search Schema for SharePoint is not working.

### Category
- [X] Fix

### CODE REVIEW

**Comment by scanum** [comment]
@tklarsen Hi Tone, could you please check and merge? Thanks

**Comment by tseward** [comment]
This PR is incomplete. It lacks the link but still has the markdown for the link. We should determine where the link goes to. @Techwriter40 may be able to assist, here.

**Comment by Techwriter40** [comment]
i was able to get this link to work.  https://go.microsoft.com/fwlink/p/?LinkID=733495. 

is this NOT the correct one??

**Comment by scanum** [comment]
@tseward

**Comment by JoanneHendrickson** [comment]
This may have been a temporary issue with the link -- it appears to be working fine in the original.  Will close PR and retain original.

**Pull request closed without merging**
