### PR TITLE
Updating to reflect new spo admin center

### PR DESCRIPTION
**Pull request by get-itips**
more info https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/bringing-onedrive-settings-into-sharepoint-admin-center-for/ba-p/2054894
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2833

### CODE REVIEW

**Comment by get-itips** [comment]
@kaarins please review

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@kaarins Kaarin can you kindly review and merge, please? Thank you

**Comment by get-itips** [comment]
@kaarins Kaarin can you kindly review and merge, please? Thank you

**Pull request merged**
