### PR TITLE
Sentence incomplete in PDF

### PR DESCRIPTION
**Pull request by dplotnikov**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1368

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dplotnikov How could we get this pr merged?

**Comment by dplotnikov** [comment]
@scanum you should engage article owner since I don't have access to merge the PR

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@kaarins Hi Kaarin, following up on this issue. Thanks!

**Comment by kaarins** [comment]
Thanks, @dplotnikov I wasn't able to simply merge this pull request to update the downloadable files, so I made the updates and submitted my own pull request. Sorry for the delay.

**Pull request closed without merging**
