### PR TITLE
Fixed typos and corrected sentence casing

### PR DESCRIPTION
**Pull request by vijayysisodia**
Fixed typos and corrected sentence casing 
a) From "ta" to "the"
b) from "pre-Onboarding" to "pre-onboarding"

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by Holland-ODSP — APPROVED** [review]

**Comment by Holland-ODSP** [comment]
Approved. Thank you!

**Comment by scanum** [comment]
Hi @Holland-ODSP - Could you kindly merge the PR? Thanks.

**Pull request merged**
