### PR TITLE
Update authentication-for-mobile-devices.md

### PR DESCRIPTION
**Pull request by msbemba**
Correct invalid links with The Importance of Smartphone Security as the other safety and security features are ouutdated.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tomresing Changes look correct. Could you please review and merge? Thanks!

**Comment by scanum** [comment]
@tomresing Any updates on merging this PR? Thanks.

**Comment by tomresing** [comment]
The rich client version of Excel on Windows doesn’t support co-authoring with any version of SharePoint Server. Some versions of Excel on Windows do support co-authoring with SharePoint Online.

**Pull request merged**
