### PR TITLE
Update instructions

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3559

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@JoanneHendrickson

**Comment by get-itips** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3540

**Comment by scanum** [comment]
@JoanneHendrickson
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@JoanneHendrickson

**Comment by get-itips** [comment]
@tiburd can you please help me here? thanks

**Pull request merged**
