### PR TITLE
Update move-or-rename-service-application-databases.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1764
Fixed Powershell

### CODE REVIEW

**Comment by MikePlumleyMSFT** [comment]
@lindspea please update the **Where:** section below the script to explain what the new variables - <OldDbName> and <NewDbName> - are.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by lindspea** [comment]
Doing more investigating.

**Comment by MikePlumleyMSFT** [comment]
My original post had some markdown problems. Looking for the new variables OldDb and NewDb to be defined with the others below the code block.

**Comment by lindspea** [comment]
> My original post had some markdown problems. Looking for the new variables OldDb and NewDb to be defined with the others below the code block.

Thanks Mike. I was a bit confused with the missing markdown, but I see the issue raiser has another query for same doc in issue #1763.  Let me know if I can do a PR once you've had a look.

**Pull request closed without merging**
