### PR TITLE
Corrected Ps to Set-SPOSite

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/949

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@kaarins Changes look correct. Could you please review and merge? Thanks!

**Comment by kaarins** [comment]
I confirmed with the product team that Set-SPOTenant is correct.

**Comment by get-itips** [comment]
@kaarins 
How are you?
Piping Set-SpoTenant to the result of Get-SpoSite just does not work, I tested that in my demo tenant.

**Comment by get-itips** [comment]
Also, the description of the example clearly states _To update multiple sites at once, use the following command as an example_

Set-SPOTenant does have a ConditionalAccessPolicy parameter so does Set-SPOSite, but as I said, the example works with Get-SPOSite as Set-SPOTenant can't handle pipelined input from SPSite objects.
Please re-review this PR in the context of the example. 
I appreciate, thank you.

**Comment by get-itips** [comment]
Hello @kaarins have you seen my comment? thanks

**Pull request closed without merging**
