### PR TITLE
Update What-is-supported-SPMT.md

### PR DESCRIPTION
**Pull request by scarolaa**
I have added "2019" as a supported version, as this is listed as a supported version on this site: https://learn.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by scarolaa** [comment]
> merge pull requests.

What's next? How does this get merged back?

**Comment by JohanFreelancer9** [comment]
> > merge pull requests.
> 
> What's next? How does this get merged back?

@scanum

**Comment by scanum** [comment]
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
