### PR TITLE
Provided an option to prevent any page modification

### PR DESCRIPTION
**Pull request by KoenZomers**
To me the article was confusing as I was looking for a way to prevent members to create any kind of pages. I found out that fiddling with the "Site Pages" feature only disables creation of modern pages, but still allows classic pages to be created. I don't really see in which scenario this would be useful. To provide people in the same scenario as me, so wanting to disallow any kind of page creation of modification, at least a hint towards how to accomplish this, I've added a hint towards how to do that to the notice box.

### CODE REVIEW

**Comment by Techwriter40** [comment]
can you paste in the URL to where this change is to be??

**Comment by Techwriter40** [comment]
@kaarins this is the page for the request.   SharePoint/SharePointOnline/let-users-create-modern-site-pages.md

**Comment by KoenZomers** [comment]
Correct, this is the URL: https://docs.microsoft.com/en-us/sharepoint/let-users-create-modern-site-pages

**Comment by kenwith** [comment]
@kaarins and @Techwriter40 - OK to merge?

**Comment by Techwriter40** [comment]
> I am OK with it, but more Kaarin's space than mine.

**Pull request merged**
