### PR TITLE
Update control-access-from-unmanaged-devices.md

### PR DESCRIPTION
**Pull request by danmyhre**
Fixed cmd - should be calling Set-SPOSite, not Set-SPOTenant when doing site-level assignment.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by kaarins** [comment]
@danmyhre The command "Set-SPOTenant -ConditionalAccessPolicy AllowLimitedAccess" is supposed to take a piped array of sites and update the site-level conditional access policy. If it's not working for you, please let us know.

**Comment by danmyhre** [comment]
It does run, but that is very confusing.  It is the wrong noun for what is being set.  I don't believe that is a documented parameter for Set-SPOTenant either.

**Comment by scanum** [comment]
@kaarins Hi Kaarins, following up on this PR. Thanks!

**Pull request closed without merging**
