### PR TITLE
Update enable-conditional-access.md

### PR DESCRIPTION
**Pull request by adeejoseph**
Resolved Issue: ADFS Update #3134

### CODE REVIEW

**Comment by adeejoseph** [comment]
This is my first time creating a PR from the public repository. (Got here by editing directly on Github's browser) I wasn't sure if this was the correct line of action. Going forward, should I complete the update in the private one? Thanks so much! @MicrosoftDocs/marveldocs-pubops

**Comment by traya1** [comment]
Hi @adeejoseph, 

If this update is high priority in nature, I would recommend closing this PR and submitting via the private repos.

In general, PubOps recommends all FTEs and vendors work in the private repos if they are able to do so. The one of the many reasons is that PubOps does not review public PRs.

If this update is not high pri, @tiburd and her team will review and merge the PR as soon as reasonably possible.

Thanks!

**Comment by tiburd** [comment]
@adeejoseph 
Hi,
I reviewed this change and merged the PR, but we do recommend creating PRs in the private repo going forward.
Thanks!!

**Comment by adeejoseph** [comment]
Thanks so much for the quick response @traya1 & @tiburd!! I'll be sure to stay in the Private repo going forward. Have a wonderful week!!

**Pull request merged**
