### PR TITLE
Update link for Conditional Access to point to Office 365 app directly

### PR DESCRIPTION
**Pull request by MicrosoftGuyJFlo**

### CODE REVIEW

**Comment by MicrosoftGuyJFlo** [comment]
#sign-off

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftGuyJFlo Could you please confirm the link? Thanks.

**Comment by scanum** [comment]
@MicrosoftGuyJFlo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Pull request closed without merging**
