### PR TITLE
Update best-practices-for-sql-server-in-a-sharepoint-server-farm.md

### PR DESCRIPTION
**Pull request by MigueGo**
the sentence "The SharePoint databases either use a stored procedure that maintains the statistics (proc_UpdateStatistics) or rely on SQL Server to do this."
is not clear enough since the approaches are totally different between versions 2013 and 2016

### CODE REVIEW

**Comment by tseward** [comment]
It does look like the HA rule was removed. I would just remove references to that rule altogether from the 2016 text, e.g. "SQL statistics are automatically updated for SharePoint 2016" or something like that.

**Comment by MigGodinho** [comment]
since the article try to address Sharepoint Server 2013 and 2016 we should really split how this part is managed in both version. we adopted a new approach that, in my opinion, should be share with our customers

**Comment by kenwith** [comment]
We did do an 'evergreen' so one article applies to multiple versions. With that said for areas where it should be split it out is totally fine to do that.

Let me loop in @MikePlumleyMSFT to see if he knows who can check this one. @tseward let's make sure your concerns are addressed too and we can loop in product team if needed.

**Comment by tseward** [comment]
The health analyzer rule still exists/performs work if required in SharePoint 2016/2019 and this change should not be made.

**Comment by MigueGo** [comment]
as already mentioned the job is still existing but there is no action in SQL side due to the logic that has been changed:
based on the internal RFC : New SEV 3 RFC : 618862 -  OnPrem: changes in proc_UpdateStatistics related to SPS2016 + SQL Issue - SQL Server CPU 100%
it was confirmed that i should request documentation update

CREATE PROCEDURE dbo.proc_UpdateStatistics
--
AS
SET NOCOUNT ON
 
#ifdef WSS
IF SERVERPROPERTY('EngineEdition') <>   V_STORE_SQLAZURE_EDITION
BEGIN
RETURN 0
END
#endif
 
DECLARE @ret int
EXEC @ret =   proc_UpdateStatisticsInternal
RETURN @ret
GO
 
you see in this logical we only call proc_UpdateStatisticsInternal when  == V_STORE_SQLAZURE_EDITION
otherwise we do a return 0 !!!

because we have decide to rely on SQL "AUTO_UPDATE_STATISTICS"

then cxs that "trust" the health rule are not having the statistics checked and updated.

**Comment by tseward** [comment]
Here's the sproc from SharePoint 2016, which doesn't match your RFC. SharePoint 2019 is similar, although it now has 3 UpdateStat sprocs that do work (proc_UpdateStatistics is just a stub to call proc_UpdateStatisticsInternal).

```
USE [databaseName]
GO

/****** Object:  StoredProcedure [dbo].[proc_UpdateStatistics]    Script Date: 9/27/2018 7:47:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[proc_UpdateStatistics]
AS
    SET NOCOUNT ON
    DECLARE @objectid int
    DECLARE @indexid int
    DECLARE @command varchar(8000)
    DECLARE @baseCommand varchar(8000)
    DECLARE @schemaname sysname
    DECLARE @objectname sysname
    DECLARE @statname sysname
    DECLARE @indexname sysname
    DECLARE @currentDdbId int
    DECLARE @bNeedFullScan bit 
    SELECT @currentDdbId = DB_ID()
    SELECT @bNeedFullScan = 0
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Starting'
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Dropping automatically created stats on user tables'
    -- Get all auto-created stats (for non-system tables 'S')
    DECLARE statsToDrop CURSOR FORWARD_ONLY READ_ONLY FOR 
    SELECT
        quotename(o.name),
        quotename(s.name)
    FROM 
        sys.stats AS s
    INNER JOIN 
        sys.objects AS o
    ON 
        o.object_id = s.object_id
    WHERE 
        (s.auto_created = 1) AND
        o.type <> 'S' 
    -- Loop through the stats we want to drop.
    OPEN statsToDrop
    FETCH NEXT
    FROM
        statsToDrop
    INTO 
        @objectname, 
        @statname
    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Dropping autostats named ' + @objectname +'.' + @statname
        SET @command = N'DROP STATISTICS ' +  @objectname + '.' + @statname;
        EXEC (@command)
        FETCH NEXT
        FROM
            statsToDrop
        INTO 
            @objectname, 
            @statname
        END
    CLOSE statsToDrop
    DEALLOCATE statsToDrop
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Updating statistics on user tables (indicies and columns)'
    DECLARE tablesToRestat CURSOR FORWARD_ONLY READ_ONLY FOR 
    SELECT 
        o.object_id,
        quotename(o.name)
    FROM 
        sys.objects AS o
    WHERE 
        o.type = 'U'
    OPEN tablesToRestat
    FETCH NEXT
    FROM
        tablesToRestat
    INTO 
        @objectid, 
        @objectname
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @bNeedFullScan = 0
        -- Lookup the name of the index
        SELECT 
            @schemaname = quotename(s.name)
        FROM 
            sys.objects AS o
        JOIN 
            sys.schemas AS s
        ON
            s.schema_id = o.schema_id
        WHERE
            o.object_id = @objectid
        IF ((@objectid = object_id(N'[dbo].[AllDocs]')) OR
           (@objectid = object_id(N'[dbo].[AllUserData]')) OR
           (@objectid = object_id(N'[dbo].[AllLinks]')) OR
           (@objectid = object_id(N'[dbo].[AllUserDataJunctions]')))
        BEGIN
            SELECT @bNeedFullScan = 1
        END
        IF (@bNeedFullScan = 1)
        BEGIN
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Statistics for ' + @schemaname + '.' + @objectname + ' are now being updated with fullscan.'      
        END
        ELSE
        BEGIN
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Statistics for ' + @schemaname + '.' + @objectname + ' are now being updated with default sampling.'
        END
        SELECT @command = 
            ' UPDATE STATISTICS ' +
                @schemaname + '.' + @objectname + ' WITH ALL, NORECOMPUTE ' 
        IF (@bNeedFullScan = 1)
        BEGIN
            SELECT @command += ', FULLSCAN'
        END
        PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Rebuilding'
        EXEC (@command)
        PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Done'
        FETCH NEXT FROM tablesToRestat INTO @objectid, @objectname
    END
    CLOSE tablesToRestat
    DEALLOCATE tablesToRestat
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Done updating statistics'
    RETURN 0
GO
```

And the `proc_UpdateStatisticsInternal` makes no mention of `V_STORE_SQLAZURE_EDITION`.

```
USE [databaseName]
GO

/****** Object:  StoredProcedure [dbo].[proc_UpdateStatisticsInternal]    Script Date: 9/27/2018 7:50:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[proc_UpdateStatisticsInternal]
AS
    SET NOCOUNT ON
    DECLARE @objectid int
    DECLARE @indexid int
    DECLARE @command varchar(8000)
    DECLARE @baseCommand varchar(8000)
    DECLARE @schemaname sysname
    DECLARE @objectname sysname
    DECLARE @statname sysname
    DECLARE @indexname sysname
    DECLARE @currentDdbId int
    DECLARE @bNeedFullScan bit 
    SELECT @currentDdbId = DB_ID()
    SELECT @bNeedFullScan = 0
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Starting'
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Dropping automatically created stats on user tables'
    -- Get all auto-created stats (for non-system tables 'S')
    DECLARE statsToDrop CURSOR FORWARD_ONLY READ_ONLY FOR 
    SELECT
        quotename(o.name),
        quotename(s.name),
        quotename(SCHEMA_NAME(o.schema_id))
    FROM 
        sys.stats AS s
    INNER JOIN 
        sys.objects AS o
    ON 
        o.object_id = s.object_id
    WHERE 
        (s.auto_created = 1) AND
        o.type = 'U' AND
        SCHEMA_NAME(o.schema_id) NOT IN ('pjpub', 'pjdraft', 'pjver', 'pjrep')
    -- Loop through the stats we want to drop.
    OPEN statsToDrop
    FETCH NEXT
    FROM
        statsToDrop
    INTO 
        @objectname, 
        @statname,
        @schemaname
    WHILE @@FETCH_STATUS = 0
    BEGIN
        BEGIN TRY
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Dropping autostats named ' + @schemaname + '.' + @objectname +'.' + @statname
            SET @command = N'DROP STATISTICS ' + @schemaname + '.' + @objectname + '.' + @statname;
            EXEC (@command)
        END TRY
        BEGIN CATCH
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Failed to Drop ' + @schemaname + '.' + @objectname +'.' + @statname + 'Exception: ' + ERROR_MESSAGE()
        END CATCH
        FETCH NEXT
        FROM
            statsToDrop
        INTO 
            @objectname, 
            @statname,
            @schemaname
        END
    CLOSE statsToDrop
    DEALLOCATE statsToDrop
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Updating statistics on user tables (indicies and columns)'
    DECLARE tablesToRestat CURSOR FORWARD_ONLY READ_ONLY FOR 
    SELECT 
        o.object_id,
        quotename(o.name)
    FROM 
        sys.objects AS o
    WHERE 
        o.type = 'U' AND
        SCHEMA_NAME(o.schema_id) NOT IN ('pjpub', 'pjdraft', 'pjver', 'pjrep')
    OPEN tablesToRestat
    FETCH NEXT
    FROM
        tablesToRestat
    INTO 
        @objectid, 
        @objectname
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @bNeedFullScan = 0
        -- Lookup the name of the index
        SELECT 
            @schemaname = quotename(s.name)
        FROM 
            sys.objects AS o
        JOIN 
            sys.schemas AS s
        ON
            s.schema_id = o.schema_id
        WHERE
            o.object_id = @objectid
        IF ((@objectid = object_id(N'[dbo].[AllDocs]')) OR
           (@objectid = object_id(N'[dbo].[AllUserData]')) OR
           (@objectid = object_id(N'[dbo].[AllLinks]')) OR
           (@objectid = object_id(N'[dbo].[AllUserDataJunctions]')))
        BEGIN
            SELECT @bNeedFullScan = 1
        END
        IF (@bNeedFullScan = 1)
        BEGIN
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Statistics for ' + @schemaname + '.' + @objectname + ' are now being updated with fullscan.'      
        END
        ELSE
        BEGIN
            PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Statistics for ' + @schemaname + '.' + @objectname + ' are now being updated with default sampling.'
        END
        SELECT @command = 
            ' UPDATE STATISTICS ' +
                @schemaname + '.' + @objectname + ' WITH ALL' 
        IF (@bNeedFullScan = 1)
        BEGIN
            SELECT @command += ', FULLSCAN'
        END
        PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Rebuilding'
        EXEC (@command)
        PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Done'
        FETCH NEXT FROM tablesToRestat INTO @objectid, @objectname
    END
    CLOSE tablesToRestat
    DEALLOCATE tablesToRestat
    PRINT CONVERT(nvarchar, GETDATE(), 126) + ': Done updating statistics'
    RETURN 0
GO
```

Of course, my T-SQL knowledge isn't super great, but from what I read here, we're still doing work on both 2016 and 2019.

**Comment by MigGodinho** [comment]
Hi Trevor,

The important here is not the function and code run in it but the logical to call this code and how the code is implemented in 2016 and >

We will never run the proc_UpdateStatisticsInternal :

#ifdef WSS
IF SERVERPROPERTY('EngineEdition') <> V_STORE_SQLAZURE_EDITION – this condition is always true for OnPrem farms
-- then we will always go in the Return 0 and never call proc_UpdateStatisticsInternal
 BEGIN
RETURN 0
END
#endif

 DECLARE @ret int
EXEC @ret = proc_UpdateStatisticsInternal
RETURN @ret
GO

Then is for this that is important that we update the documentation with the diff between 2013 and 2016



Best regards,

Miguel Godinho

**Comment by tseward** [comment]
I appreciate what you're saying, but the sprocs on SharePoint 2016/2019 on content databases don't match the sproc T-SQL you're providing here.

**Comment by MigGodinho** [comment]
there is the pro_updatestatistics in a SPS 2016 content database : 
USE [WSS_Content_158b4fa7a3f045949750c989eae574d0]
GO
/****** Object:  StoredProcedure [dbo].[proc_UpdateStatistics]    Script Date: 9/27/2018 6:16:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[proc_UpdateStatistics]
AS
    SET NOCOUNT ON
    IF SERVERPROPERTY('EngineEdition')  <> 5
    BEGIN
        RETURN 0
    END
    DECLARE @ret int
    EXEC @ret = proc_UpdateStatisticsInternal
    RETURN @ret

before you call  proc_UpdateStatisticsInternal there is a test and this test is never true for OnPrem Farms

**Comment by larspl** [comment]
Hi just my 2cents, I disable after setup the SharePoint based jobs for sql maintenance and use this:  I prefer ola‘s sql maintenance solution https://ola.hallengren.com. This will work in all environments. Cheers Lars

**Comment by kenwith** [comment]
@bentoncity --  Steve, this one is beyond my knowledge.. :)

**Comment by MigGodinho** [comment]
Ola Hallengreen's scripts are well known and customer talk to me about them but we are talking about what we are provide like information to our customers. could you suggest to use Ola's scripts ?

**Comment by MigGodinho** [comment]
i mean in a TechNet article

**Comment by larspl** [comment]
In my years with SharePoint Server since Version 2001 i‘l take a Deep look into the sql side. All the time there are runtime issues in sql server. If you like to have a performance Backend you need to review the sql stats Updates , the Index rebuild / reorg and ofcourse the Backup. All this topics are covered by ola Solution. Il suggest ola in all cases. also for stretch and hybrid scenarios.

**Comment by MigGodinho** [comment]
actually it s not really the point in this pull request. previously many of the customer relies on the fact that in SPS 2010 and 2013 we have a timer job that is supposed to take care of statistics and fragmentation. 
but it's no more true in SPS 2016 while the timer job still exist but it doesn't do anything. It's clear that this change can confused some of our customer and for this we should be more clear in our article

**Comment by Techwriter40** [comment]
@bentoncity review this please and then merge.

**Comment by kenwith** [comment]
I shot an email to Steve @bentoncity so he can take a look.

**Comment by MigGodinho** [comment]
any update ?

**Comment by bentoncity** [comment]
Miguel, as per the earlier "New SEV 3 RFC" thread you were in, I don't see what I need to revise in this article. According to Sean, they aren't going to create a KB article for it. When I updated this topic for SharePoint 2016, SQL PMs advised me to state "or rely on SQL Server to do this".

**Comment by MigGodinho** [comment]
the point is that we maintain so approach during 2 SPS versions (2010 and 2013) and suddenly we change our approach and we are not informing our customers. We bring some confusing in our customers because we just write "either use a stored procedure that maintains the statistics (proc_UpdateStatistics) or rely on SQL Server to do this." 
but which version is using SQL server and which one is using proc_UpdateStatistics. 
it's fair enough to provide this information to our customers and let them now what they should care about, let SPS doing the job or implement maintenance plan.

**Comment by kenwith** [comment]
@MigueGo - this discussion is out of my area of expertise.. I am not sure what to do with this one.. leave it open and see if @bentoncity can do anything with the doc or close it? What do you want to do with it?

**Comment by MigueGo** [comment]
Let me wrap-up my request: the current statement is confusing: 
"The SharePoint databases either use a stored procedure that maintains the statistics (proc_UpdateStatistics) or rely on SQL Server to do this."

I suggest to replace it by making explicit what should be done depending on the SharePoint version.
I just updated the changes in the PR to reflect this.

**Comment by kenwith** [comment]
@MigueGo - thanks for the updates and getting this to a closed out state. @bentoncity - OK to merge now?

**Comment by MigGodinho** [comment]
any update in this ?

**Comment by AndreaBarr** [comment]
@bentoncity is it okay to merge this now?

**Comment by bentoncity** [comment]
@AndreaBarr yes, go ahead and merge this.

**Comment by MigueGo** [comment]
well done !

**Pull request merged**
