### PR TITLE
Update sensitive-by-default.md

### PR DESCRIPTION
**Pull request by Pulkit-Sachan**

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@SanjoyanM can you review?

**Review by SanjoyanM — APPROVED** [review]
This is correct. Approved.

**Pull request merged**
