### PR TITLE
Update cmdlets

### PR DESCRIPTION
**Pull request by thibaultchatiron**

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@robmazz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@robmazz can you review this PR?

**Comment by robmazz** [comment]
@MikePlumleyMSFT - these changes were made earlier, closing.

**Pull request closed without merging**
