### PR TITLE
Fix for issue 810

### LINKED ISSUE #810: Article does not align with "Account permissions and security settings in SP Servers"
This article does not align with the naming conventions used in https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016. For more information about naming conventions for accounts see #319 

I will provide a PR for this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0151f1-a178-6675-31df-19b130f4e1c2
* Version Independent ID: 10fb7e98-2870-68c5-5ad2-791beaaca583
* Content: [Plan for administrative and service accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

### PR DESCRIPTION
**Pull request by andikrueger**
Closes #810 

@tseward Could you do a review of the proposed changes?

BTW. I do not know how git interpreted renames - but in this case, its totally wrong....
It should be:
account-permissions-and-security-settings-in-sharepoint-server-2016.md --> account-permissions-and-security-settings-in-sharepoint-server.md
and not
account-permissions-and-security-settings-in-sharepoint-server-2016.md --> group-permissions-in-sharepoint-server.md

### CODE REVIEW

**Comment by tseward** [comment]
@andikrueger I'm confused as to what this change is for and why there are file renames as part of this. I had submitted PRs for the articles a couple of days ago.

**Comment by andikrueger** [comment]
On Friday I did start to get this change prepared and did not check for WIP today. Sorry about it! 

Renaming: 

As both articles "account-permissions-and-security-settings-in-sharepoint" for SP 2013 and SP2016/2019 are so similar - except Group Permissions and Excel Services, I did not see a reason to keep on with separate files. That's why I did rename the 2016 article. This was the most polished article, we have so far. For a better readability and to get rid of duplication.

**Comment by tseward** [comment]
OK, since our PRs would conflict, let's talk about this one offline. I'll send you an email.

**Comment by scanum** [comment]
@tseward @andikrueger Any updates on this? Thanks!

**Comment by tseward** [comment]
@scanum Andi and I are reviewing other changes he has put forth. I will be spending time on this next week.

**Comment by scanum** [comment]
@tseward Hi Trevor, any updates on this? Thanks!

**Comment by andikrueger** [comment]
We are still discussing some changes. I would close this PR for now, cause we would need to do additional changes. Is this okay for you?

**Comment by scanum** [comment]
@andikrueger Thanks!
@officedocsbot close

**Pull request closed without merging**
