### PR TITLE
Update understanding-permission-levels.md

### PR DESCRIPTION
**Pull request by alinefmr**
Updating "Everyone except external users" note under "Default Permission Levels".

### CODE REVIEW

**Comment by tseward** [comment]
> "Everyone except external users" cannot be granted any permissions and people must be explicitly granted permissions.

This statement is inaccurate. A user with appropriate rights can grant that group access. Company Administrator is also not automatically granted SCA. It may be worth clarifying. The PR could also use some word smithing, removing parenthesis and filler words like 'also'.

**Comment by alinefmr** [comment]
"Everyone except external users" cannot be granted any permissions and people must be explicitly granted permissions.
You said: _"This statement is inaccurate. A user with appropriate rights can grant that group access. "_

Actually, a user with appropriate rights can grant access, but changes will be automatically reverted back to default after any additional modifications are made at Group level. For Public team sites, for example, if "Everyone except external users" is removed from SharePoint's Members group, it will look like it's been taken into effect until a new user is added to the Group, and original Privacy settings-related permissions will be enforced.

I agree this behavior needs clarification. Also, (sharepoint/default-sharepoint-groups) looks like a more fitting place thos such information.

**Comment by tseward** [comment]
I was able to add a user to a SharePoint group without losing 'Everyone except external users' as a member of that SharePoint group.

**Comment by alinefmr** [comment]
Add a user to the AD Group associated with the Modern team site.

Private Modern Team site --> if you add "Everyone except external users" to any SharePoint Groups, it will be removed.

Public Modern Team site --> remove it from SharePoint's Members group. It will be re-added.

**Comment by tseward** [comment]
With regards to private Team sites, that is not the behavior I'm observing.

**Comment by alinefmr** [comment]
[EveryoneExceptExternal_ReproPublicAndPrivate.docx](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/3119375/EveryoneExceptExternal_ReproPublicAndPrivate.docx)

**Comment by alinefmr** [comment]
I had a Premier support case opened related to this, closed as "expected behavior".

**Comment by tseward** [comment]
Nope, I cannot reproduce. I'm able to add members to a private Modern Team site without 'Everyone except external users' being removed.

**Comment by alinefmr** [comment]
Give it some minutes. It's not real time, it just took me 5 minutes to see it happening, 15 minutes ago.

**Comment by tseward** [comment]
It's been ~3 hours, no change.

**Comment by alinefmr** [comment]
I was just able to reproduce in another tenant. See https://onedrive.visualstudio.com/STS/_workitems/edit/701069 , I can also demo it to you if needed.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by kaarins** [comment]
@alinefmr @tseward I have escalated this with the product team to clear things up. Thank you!

**Comment by coupalm** [comment]
If I may add to this discussion, If we are allowed to set permissions for "Everyone Except External Users" to read and it will revert back to edit by a job, there is no justification to provide the ability to change permission in the site setting menu. At least if you still provide the ability to do it, you must provide a CLEAR message of this behavior in the UI and not just in the product documentation because of the repercussion of the behavior. This has a major impact on the decision to choose between a standard team site and a O365 group public site. Currently site owners think the site is read-only to all other users but find out later on about these users updating their documents... I confirm this behavior occuring in tenants in Canada and US. Thanks.

**Comment by coupalm** [comment]
Last comment, I had a ticket with support for this behavior of permissions reverting for "Everyone except external users" on public site and they were not able to reproduce. However escalation team confirmed this was a normal behavior. So it looks like it does not behave the same everywhere.

**Comment by alinefmr** [comment]
@coupalm "set permissions for "Everyone Except External Users" to read and it will revert back to edit " is not what happens. The behavior is: on public groups, removing "Everyone except external users" from any SharePoint groups (not just downgrading from edit to read) will be allowed in the UI, but later reverted back by a job. And on private groups, adding EEEU to any SharePoint groups with any permission levels will be allowed in the UI, but later removed by a job. Agree on the clear message in the UI pointing that EEEU permissions are defined by site's privacy settings.

**Comment by coupalm** [comment]
I fully understand your definition. Thanks for the clarification.

IMOO, having a background job changing permission is pretty scarry...
And also, before publishing this behavior, make sure it is working everywhere because, like @tseward , the support team I've contacted was not able to reproduce.

Note: When creating O365 public group, the privacy drop down should say for “Public”: “Anyone in the organization can **update/delete** group content” instead of “Anyone can **see** group content”. Same thing in SP central admin.

Thanks.

**Comment by coupalm** [comment]
Maybe not the place for the following, but I want to give my point of view on this behavior for public group site if someone from Microsoft is reading this post.

The issue I foresee is a lot of people have decided to create public group site thinking they could have EEEU in read only mode (and also because it looked to be the new way to proceed by creating SP site connected to O365 group and then connect to team)

If EEEU will always have Edit permission on public group site, I'm sure a lot of admin will need to recreate these SP public sites to team sites not connected to O365 groups to be able to provide read only access at the top level. The other way would be to break inheritance on all SharePoint libraries and lists which does not really make sense. 

Also, If I'm not mistaken, for long period of time it was only possible to create modern sites connected to O365 groups in the UI using the SharePoint page or in the new SharePoint admin. This has forced people to create group connected sites instead of just modern team site. Not all business had the skills to use PowerShell to create modern team sites not connected to O365 group at that time.

Probably this permission behavior is related to the fact that other services in the group like planner can’t provide read only access. But this is clearly a bad implementation regarding SharePoint.

Honestly, I think this will cause a major pain to a lot of people when they will find out.

**Comment by jaredtl4587** [comment]
I have not been able to connect to anything. I've been having issues left and right that I dont understand. For one my phone isn't ios, its samsung s9+. And there's no way for me to login to my account because it's asking me to verify via my old number which I cant access from a new number. On May 1, 2019 6:49 PM, Martin Coupal <notifications@github.com> wrote:Maybe not the place for the following, but I want to give my point of view on this behavior for public group site if someone from Microsoft is reading this post.

The issue I foresee is a lot of people have decided to create public group site thinking they could have EEEU in read only mode (and also because it looked to be the new way to proceed by creating SP site connected to O365 group and then connect to team)

If EEEU will always have Edit permission on public group site, I'm sure a lot of admin will need to recreate these SP public sites to team sites not connected to O365 groups to be able to provide read only access at the top level. The other way would be to break inheritance on all SharePoint libraries and lists which does not really make sense.

Also, If I'm not mistaken, for long period of time it was only possible to create modern sites connected to O365 groups in the UI using the SharePoint page or in the new SharePoint admin. This has forced people to create group connected sites instead of just modern team site. Not all business had the skills to use PowerShell to create modern team sites not connected to O365 group at that time.

Probably this permission behavior is related to the fact that other services in the group like planner can’t provide read only access. But this is clearly a bad implementation regarding SharePoint.

Honestly, I think this will cause a major pain to a lot of people when they will find out.

**Comment by coupalm** [comment]
> @coupalm "set permissions for "Everyone Except External Users" to read and it will revert back to edit " is not what happens. The behavior is: on public groups, removing "Everyone except external users" from any SharePoint groups (not just downgrading from edit to read) will be allowed in the UI, but later reverted back by a job. And on private groups, adding EEEU to any SharePoint groups with any permission levels will be allowed in the UI, but later removed by a job. Agree on the clear message in the UI pointing that EEEU permissions are defined by site's privacy settings.

@alinefmr , FYI I've performed to following on a public group site 2 days ago: 
1) Remove EEEU from Site members. 
2) Create a new SharePoint group with read permission and add EEEU in it. 
3) Add a new member (to perform an update on the group members to see if the job will be triggered). 
4) 2 days later no changes.

So is this a normal behavior? The job did not put back EEEU in the members group because I added it to another SP Group (other from the regular owners, members, visitors SP group)?

I don't understand this background job logic. 

@kaarins If you have any info from escalation teams, please share it as I need to know how permissions work on public group site as this is crucial for sites/permissions architecture. If we will not be allowed to  set read access to EEEU, I will need to convert most of my customers public group sites to standard SP team sites to get full flexibility on permissions management.

Thanks!

**Comment by alinefmr** [comment]
@coupalm - In order to repro the behavior, DO NOT perform step 2. Simply remove EEEU from Members, add any other user as Domain group member and it will bring EEEU back to SharePoint in Public group sites.

Background job just makes sure EEEU has been added to a SharePoint Group (no matter with what Permission level) for Public group sites. For private sites, it removes EEEU from any SharePoint groups (not even Read is allowed). In a summary, presence of EEEU is defined by Privacy settings and enforced by a background job.

**Comment by coupalm** [comment]
@alinefmr , ok but how come in the first example I gave in this thread, where I've changed permissions level of EEEU from edit to read, it was revert back to Edit by the job?

**Comment by alinefmr** [comment]
@coupalm  - I'll leave that for @kaarins to answer, as she's checking with PG, but I can ensure the behavior I described is reproducible 100% of times in four different tenants (including a DvNext tenant).

**Comment by coupalm** [comment]
@alinefmr , I totally agree with what your are saying that the EEEU is being put back if removed from a public group by the job. 

It is the permission changes on EEEU that is causing me problem. I've been able to reproduced on 3 differents tenants in Canada and US with audit log showing Microsoft\ServiceAccount remove the account from the visitors SP group and put it back in the Members SP group instead of leaving it in the visitors SP group. Other people are having the same issue. So let see what is the PG response. Thanks for your feedback.

With powershell provisionning: https://techcommunity.microsoft.com/t5/SharePoint/Pnp-provisoning-issue-with-permissions-for-Everyone-except/td-p/388518

In Europe: https://techcommunity.microsoft.com/t5/SharePoint/Everyone-except-external-users-disappears-form-Group-Visitors/m-p/388808/highlight/true#M28344

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by alinefmr** [comment]
It looks like I cannot resolve these conflicts or merge these changes. Should I just close, so someone else can move forward with the changes? Please advise. Thanks.

**Comment by scanum** [comment]
@MikePlumleyMSFT Hi Mike, changes look correct could you please merge? Thanks!

**Comment by scanum** [comment]
@alinefmr Hi Aline, Sowjanya has made a change to the doc. I will ask the author to merge. Thanks

**Pull request merged**
