### PR TITLE
Add Omnissa Horizon page

### PR DESCRIPTION
**Pull request by haroldwongms**
Add Omnissa Horizon page with instructions to configure OneDrive.

### CODE REVIEW

**Comment by haroldwongms** [comment]
I have corrected the alt text issue.

**Comment by haroldwongms** [comment]
#sign-off

**Comment by shdyas** [comment]
@maggierui Harold is looking for someone to work with from content team to get this published.

**Comment by jacktremper** [comment]
@haroldwongms this isn't the type of content we would want to host within the SharePoint/OneDrive repo as that content set is specific to the apps/services. This information is specific to the Horizon virtual apps and how they work, not specific to configuring OneDrive/SharePoint.

Also, this content is already publicly available here: https://kb.omnissa.com/s/article/6000052. No need to duplicate it on our site.

**Comment by haroldwongms** [comment]
Jack,

I understand the reasoning. However, there is a page for Citrix who is a competitor to Omnissa: Set up OneDrive in Citrix Virtual Apps - SharePoint in Microsoft 365 | Microsoft Learn<https://learn.microsoft.com/en-us/sharepoint/onedrive-in-citrix-virtual-apps-deployment-guide>.

Omnissa (formerly VMware) is asking why we are playing favorites. That's the reason why I put in the PR for Omnissa. Can you provide an explanation for this so that I can communicate to Omnissa? Thank you.

Harold Wong
Strategic Partnership CTO - VMware by Broadcom | IBM
Work: (425) 706-3501
Mobile: (602) 570-1214

Please excuse any misspellings / errors as I am using speech to text software (Dragon Naturally Speaking) to compose this email.

**Comment by jacktremper** [comment]
@haroldwongms Got it and that makes sense. Didn't realize we had one for Citrix.

@MachelleTranMSFT can you get this added to the same node as this topic: https://learn.microsoft.com/en-us/sharepoint/onedrive-in-citrix-virtual-apps-deployment-guide

**Comment by haroldwongms** [comment]
Jack,

I haven't seen any response or movement on Machelle's part. Is there any way you can approve the PR? Thank you.

Harold Wong
Strategic Partnership CTO - VMware by Broadcom | IBM
Work: (425) 706-3501
Mobile: (602) 570-1214

Please excuse any misspellings / errors as I am using speech to text software (Dragon Naturally Speaking) to compose this email.

**Comment by haroldwongms** [comment]
#sign-off

**Comment by MachelleTranMSFT** [comment]
@haroldwongms - We'll need to remove the images because they're too small. The article has been updated to reflect Microsoft product and writing style guide.

**Comment by haroldwongms** [comment]
@MachelleTranMSFT - What is the size requirement?

**Comment by MachelleTranMSFT** [comment]
> @MachelleTranMSFT - What is the size requirement?

435 pixels wide is the minimum.

**Comment by MachelleTranMSFT** [comment]
I'm going to go ahead and merge the PR since we can always add the images later on.

**Comment by garycentric** [comment]
@haroldwongms , @MachelleTranMSFT 
Harold, please make your future contributions in the private repo(s) instead of the public. You have Microsoft credentials.

**Comment by haroldwongms** [comment]
[like]  Harold Wong (he / him) reacted to your message:
________________________________

**Pull request merged**
