### PR TITLE
Update crawled-and-managed-properties-overview.md

### PR DESCRIPTION
**Pull request by Mindzweeper**
We made ModifierNames searchable.

### CODE REVIEW

**Comment by wobba** [comment]
This one should not be merged. ´ModiferNames´ is not searchable in the SharePoint schema. @Mindzweeper care to elaborate?

**Comment by wobba** [comment]
This one has been stale for a while with no comment from @Mindzweeper, so I propose we close it.

**Comment by Mindzweeper** [comment]
@wobba I missed the original replies here because I was on vacation first week of April.  I will get verification early next.

**Comment by scanum** [comment]
@Mindzweeper hope all is well. Is there an update for this PR? Thanks!

**Comment by Mindzweeper** [comment]
@scanum we can close this PR.  I have verified that ModifierNames is not searchable in the schema.

**Pull request closed without merging**
