### PR TITLE
Added line breaks to PowerShell commands to make the commands correct…

### PR DESCRIPTION
**Pull request by cvollmann**
… and clearer

### CODE REVIEW

**Comment by kenwith** [comment]
@cvollmann - I am wondering if adding the line break will cause the Copy Code to have a problem since it would copy the line break too? Would you be able to test if it still works? Here is article on docs: https://docs.microsoft.com/en-us/sharepoint/administration/back-up-a-search-service-application 

It also looks like there is an issue that needs to be cleaned up with the 'code' section after that it says "Where" in code section but that probably shouldn't be in code section.

I can go ahead and clean this up unless you would want to? Let me know. Thanks for taking the time to make the docs better!

**Comment by tseward** [comment]
@kenwith These line breaks are appropriate. The original doc is mis-formatted as the cmdlets should be on separate lines. This article has a few more formatting issues that can be addressed in another PR.

**Comment by cvollmann** [comment]
I should mention that this was only a quick fix for the cmdlets. Better to start with something than nothing on this article.

The cmdlets are working for me with the new line breaks.

**Comment by kenwith** [comment]
@cvollmann and @tseward - ok perfect. Merged this and will keep an eye for any more PRs too. Thanks for fixes. Much appreciated!

**Pull request merged**
