### PR TITLE
Updated permission removal/addition with broken inheritance sentence in what-is-permissions-inheritance.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2189.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@dariomws the original text is correct.

**Comment by dariomws** [comment]
@MikePlumleyMSFT I tested it and only removal works for me, not addition, in the same way the user commented.

Anyway, I'll let the user know that this sentence is correct.

**Pull request closed without merging**
