### PR TITLE
Proposing changing from Use to Enable OnDemand

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1478

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kaarins** [comment]
The policy is actually called "Use OneDrive Files On-Demand" and its states are Enabled, Disabled, or Not Configured. It's important that this article aligns with the policy name.

**Pull request closed without merging**
