### PR TITLE
Update the-security-token-service-is-not-available.md

### PR DESCRIPTION
**Pull request by dariomws306**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1382

### CODE REVIEW

**Comment by MikePlumleyMSFT** [comment]
@tseward can you review this PR?

**Comment by dariomws306** [comment]
> @tseward can you review this PR?

Hi @MikePlumleyMSFT, thank you for your comment. In the issue @tseward left a comment and he is not agree with this update. I'm agree with him but I have create the PR to have other opinion.
So, I think we shouldn't apply this update.

**Comment by tseward** [comment]
Actually, I'm good with this one. Only requested change of verbiage: 


> 1. Check the event logs [TS - Which event log? Be specific.] for event ID 8311 which may indicate the STS certificate has expired.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.
--

**Comment by dariomws306** [comment]
Thanks @tseward, let's apply it. I have updated the PR, please check if you think it's ok now.

**Pull request merged**
