### PR TITLE
Update pre-provision-accounts.md

### PR DESCRIPTION
**Pull request by v-pajorg**
As a prerequisite (SharePoint License assigned). As per now it only mentions that you need to be a global or sharepoint admin. Please validate this with Product Group.

### CODE REVIEW

**Comment by kenwith** [comment]
@v-pajorg - thank you for taking the time to make the docs better, much appreciated.

@kaarins - OK to merge?

**Comment by kaarins** [comment]
I don't think this is required, but I added Vesa to confirm.

**Comment by kenwith** [comment]
@VesaJuvonen - OK to merge?

**Comment by VesaJuvonen** [comment]
All good and ready to go.

**Pull request merged**
